apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs7319-quote-api-deployment
  labels:
    app: cs7319-quote-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cs7319-quote-api
  template:
    metadata:
      labels:
        app: cs7319-quote-api
    spec:
      containers:
      - name: cs7319-quote-api-container
        image: cs7319-quotes-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # The port your Flask app listens on
        env:
        - name: FLASK_ENV
          value: production
        # Add other environment variables as needed, e.g., database connection strings
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-credentials
        #       key: url
---
apiVersion: v1
kind: Service
metadata:
  name: cs7319-quote-api-service
spec:
  selector:
    app: cs7319-quote-api
  ports:
  - protocol: TCP
    port: 80 # The port the service will listen on
    targetPort: 8080 # The port on the container where the Flask app is running
  type: ClusterIP # Use port-forward for local access in Minikube