[tool.ruff]
select = ["E", "F"]
ignore = ["D212", "D200"]
line-length = 79

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
