apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-mydeploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: quote
          image: chow1668/myquotes:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: quote-svc
spec:
  selector:
    app: quote
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30083
